### ISSUE TITLE
Renamed EVERY track Common_pipistrelle_Jules_Agate

### ISSUE THREAD

**Issue by StevieDavies** [x43x61x69/Metarminator#9]
This product just renamed every track in my iTunes library to Common_pipistrelle_Jules_Agate!  It removed every bit of metadata and now none of my music works.

**Comment by x43x61x69** [comment]
Hi @StevieDavies !

I'm sorry to hear that.

Your music files are still playable even when all the metadata was stripped, just that it's no way to recover those metadata unless you have a backup.

Although Metarminator was tested by the developer and Apple Review Team, it's still, not recommended to drag in your entire iTunes Library to Metarminator for modifying (in case something went wrong, not many people have their iTunes Library backuped due to the size it took), and please always make backups before you make changes to important files to prevent either programmatic or human error.

As the information you indicated, this should not be an error regarding to Metarminator itself, as the string "Common_pipistrelle_Jules_Agate" is not part of it's code or possible output of any kind. By default, Metarminator will warn the users when they try to modify multiple files at once unless they choose to mute those warnings.

Hope this answers your questions.

Best,
Cai
